num_process: 10
pc_path: ./waymo/waymo_format/validation_new/pc/
data_path: ./mmdetection3d/results/waymo-car/kitti_results.bin
gt_path: ./waymo/waymo_format/validation_new/gt
target_path: ../../datasets/mmdet3d_pp
mode: val
expand_proposal_meter: 3
nframe: 1

