num_process: 10
pc_path: /mnt/truenas/scratch/zhichao.li/workspace/mmdetection3d/data/waymo/waymo_format/validation_new/pc/
data_path: /mnt/truenas/scratch/zhichao.li/workspace/mmdetection3d/results/waymo-car/kitti_results.bin
gt_path:  /mnt/truenas/scratch/zhichao.li/workspace/mmdetection3d/data/waymo/waymo_format/validation_new/gt/
target_path: ../../datasets/mmdet3d_5_frame
mode: val
expand_proposal_meter: 3
nframe: 5
